### ISSUE TITLE
Possibly useful report

### ISSUE THREAD

**Issue by StevenACoffman** [Khan/genql#1]
I didn't investigate too closely, but I didn't want to forget it in case this is useful. Over the weekend I thought I'd make a githubstatus cli tool and got this reproducible error:
```
$ git clone git@github.com:Khan/genql.git
$ cd genql/
$ go install
$ cd ..
$ mkdir githubstatus
$ cd githubstatus
$ git init
$ go mod init github.com/StevenACoffman/githubstatus
$ curl https://developer.github.com/v4/public_schema/schema.public.graphql -o schema.public.graphql
genql schema.public.graphql

invalid config file schema.public.graphql: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `` into generate.Config
```
Another weekend I might be able to spend more time on figuring it out, but thought I'd pass it on in case I forgot and it might be helpful in the meantime.

**Comment by benjaminjkraft** [comment]
(Whoops, apparently I wasn't watching this repo!  Sorry for the delay.)

It looks like you're just calling genql wrong -- the argument is a config file, not a schema file.  (In particular, it actually cares about three files: a schema, a document with your queries, and the output file.)  The example/README.md should have slightly clearer instructions.
